version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=wellness
      - JWT_SECRET=wellness_app_secret_key_for_development
      - SAHHA_API_KEY=placeholder_sahha_api_key
      - ASLEEP_API_KEY=placeholder_asleep_api_key
      - PASSIO_API_KEY=placeholder_passio_api_key
      - STRAVA_CLIENT_ID=placeholder_strava_client_id
      - STRAVA_CLIENT_SECRET=placeholder_strava_client_secret
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - neo4j
    networks:
      - wellness-network

  neo4j:
    image: neo4j:4.4
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/wellness
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - wellness-network

networks:
  wellness-network:
    driver: bridge

volumes:
  neo4j_data:
  neo4j_logs:
